# Generated by Django 4.2.9 on 2024-05-11 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('region', models.CharField(blank=True, max_length=128, null=True, verbose_name='region')),
                ('detail_info', models.TextField(blank=True, null=True, verbose_name='detail_info')),
                ('creator_email', models.EmailField(max_length=254, verbose_name='creator_email')),
                ('creator_contact_information', models.CharField(blank=True, verbose_name='creator_contact_information')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'users_posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(verbose_name='comment body')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'post_comments',
            },
        ),
    ]
