# Generated by Django 4.2.9 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='region',
            field=models.TextField(blank=True, null=True, verbose_name='region'),
        ),
    ]
