# Generated by Django 4.2.9 on 2024-05-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_remove_posts_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='goal_progress',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='monobank_link',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='now_progress',
        ),
        migrations.AddField(
            model_name='posts',
            name='detail_info',
            field=models.TextField(blank=True, null=True, verbose_name='detail_info'),
        ),
        migrations.AddField(
            model_name='posts',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='region'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(verbose_name='comment body')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'post_comments',
            },
        ),
    ]
